/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practicajdbc;

import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class Consultas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Consultas.class.getName());

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        this.setTitle("Consultas JDBC");
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLike = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtJoin = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtGroupBy = new javax.swing.JTextArea();
        btnLike = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        btnGroupBy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consultas con JDBC");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setText("LIKE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setText("JOIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setText("GROUP BY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        txtLike.setColumns(20);
        txtLike.setRows(5);
        txtLike.setText("SELECT columnas\nFROM nombre_tabla\nWHERE columna LIKE 'valor';");
        jScrollPane1.setViewportView(txtLike);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        txtJoin.setColumns(20);
        txtJoin.setRows(5);
        txtJoin.setText("SELECT columnas\nFROM tabla1\nJOIN tabla2\nON tabla1.columna = tabla2.columna\nWHERE condicion;");
        jScrollPane2.setViewportView(txtJoin);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        txtGroupBy.setColumns(20);
        txtGroupBy.setRows(5);
        txtGroupBy.setText("SELECT columna1, columna2, funcion_agregacion(columna3)\nFROM nombre_tabla\nWHERE condicion\nGROUP BY columna1, columna2\nHAVING condicion_agregada;");
        jScrollPane3.setViewportView(txtGroupBy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel2.add(jScrollPane3, gridBagConstraints);

        btnLike.setBackground(new java.awt.Color(51, 204, 0));
        btnLike.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnLike.setText("EJECUTAR");
        btnLike.setPreferredSize(new java.awt.Dimension(130, 18));
        btnLike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLikeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 45, 15, 45);
        jPanel2.add(btnLike, gridBagConstraints);

        btnJoin.setBackground(new java.awt.Color(51, 204, 0));
        btnJoin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnJoin.setText("EJECUTAR");
        btnJoin.setPreferredSize(new java.awt.Dimension(130, 18));
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(15, 45, 15, 45);
        jPanel2.add(btnJoin, gridBagConstraints);

        btnGroupBy.setBackground(new java.awt.Color(51, 204, 0));
        btnGroupBy.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGroupBy.setText("EJECUTAR");
        btnGroupBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupByActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 45, 20, 45);
        jPanel2.add(btnGroupBy, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        // TODO add your handling code here:

        String resultado = txtLike.getText();

        JOptionPane.showMessageDialog(this, resultado, "Consulta realizada", JOptionPane.INFORMATION_MESSAGE );

    }//GEN-LAST:event_btnLikeActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        // TODO add your handling code here:

        String resultado = txtJoin.getText();

        JOptionPane.showMessageDialog(this, resultado, "Consulta realizada", JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_btnJoinActionPerformed

    private void btnGroupByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupByActionPerformed
        // TODO add your handling code here:
        
        
             
        String resultado = txtGroupBy.getText();

        JOptionPane.showMessageDialog(this, resultado, "Consulta realizada", JOptionPane.INFORMATION_MESSAGE );
   
    
        
    }//GEN-LAST:event_btnGroupByActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consultas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGroupBy;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnLike;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtGroupBy;
    private javax.swing.JTextArea txtJoin;
    private javax.swing.JTextArea txtLike;
    // End of variables declaration//GEN-END:variables
}
